[workspace]

members = [
  "abstutil",
  "convert_osm",
  "ezgui",
  "game",
  "geom",
  "gtfs",
  "headless",
  "importer",
  "kml",
  "map_editor",
  "map_model",
  "sim",
]

# See https://doc.rust-lang.org/cargo/reference/profiles.html#overrides. This
# compiles all external dependencies as release mode, yielding great runtime
# speed, but only paying the cost of slow compilation once (since we don't
# update dependencies often).
[profile.dev.package."*"]
opt-level = 3

[patch.crates-io]
glutin = { git = "https://github.com/dabreegster/glutin" }
