[package]
name = "gtfs"
version = "0.1.0"
authors = ["Dustin Carlino <dabreegster@gmail.com>"]
edition = "2018"

[dependencies]
abstutil = { path = "../abstutil" }
geom = { path = "../geom" }
itertools = "0.8.0"
serde = "1.0.110"
transitfeed = { git = "https://github.com/dabreegster/transitfeed" }
